# agent-track — AgentSquad Makefile
# Generated by init-agent-team v1.0.0 on 2026-03-12
#
# Ownership: init-agent-team generates this scaffold.
# DevOps Engineer owns it after initial generation.
#
# KEY STRATEGY: All agents share GEMINI_API_KEY by default.
#   Per-agent keys (GEMINI_KEY_BACKEND etc.) override when set in .env.team.
# MODEL STRATEGY: No -m flag (broken in gemini-cli 0.32.1+).
#   Model set via GEMINI_MODEL env var. Default: gemini-3-flash (20 RPD free).
#   Use *-lite targets for Gemma tier (14,400 RPD free).
#
# Requires: GNU Make (on macOS: brew install make, then use gmake)
# Usage:
#   make backend  TASK="implement the SQLite connection module"
#   make backend-lite  TASK="scaffold CRUD boilerplate"  # Gemma, 14,400 RPD
#   make team-health                                     # 0 RPD credential check

-include ~/.agent-team/.env.team
export

GEMINI_FLAGS := --approval-mode=yolo
OUTPUT_DIR   := agent-output

# Key resolution: per-agent key takes precedence over shared key
BACKEND_KEY  := $(or $(GEMINI_KEY_BACKEND),$(GEMINI_API_KEY))
FRONTEND_KEY := $(or $(GEMINI_KEY_FRONTEND),$(GEMINI_API_KEY))
QA_KEY       := $(or $(GEMINI_KEY_QA),$(GEMINI_API_KEY))
DEVOPS_KEY   := $(or $(GEMINI_KEY_DEVOPS),$(GEMINI_API_KEY))
CONSULT_KEY  := $(or $(GEMINI_KEY_CONSULTANT),$(GEMINI_API_KEY))

# Model defaults (override in .env.team or environment)
# gemini-2.5-flash-lite: confirmed working, 20 RPD free tier
# gemini-3-flash-preview: alias for Gemini 3 Flash, 20 RPD free tier
# NOTE: gemma-3-*-it models do NOT work with gemini-cli (no function calling support)
BACKEND_MODEL  ?= gemini-2.5-flash-lite
FRONTEND_MODEL ?= gemini-2.5-flash-lite
QA_MODEL       ?= gemini-2.5-flash-lite
DEVOPS_MODEL   ?= gemini-2.5-flash-lite
CONSULT_MODEL  ?= gemini-3-flash-preview
GEMMA_MODEL    ?= gemini-2.5-flash-lite

.PHONY: backend frontend qa devops consult \
        backend-lite frontend-lite qa-lite \
        team-health team-health-live clean-output help \
        test lint typecheck dev

backend: ## Dispatch Backend Engineer (gemini-3-flash, 20 RPD)
	@mkdir -p $(OUTPUT_DIR)
	@{ \
	  _tmp=$$(mktemp /tmp/agentsquad-XXXXXX); \
	  printf '%s' "$(TASK)" > "$$_tmp"; \
	  GEMINI_API_KEY=$(BACKEND_KEY) GEMINI_MODEL=$(BACKEND_MODEL) \
	    gemini --prompt "$$(cat $$_tmp)" $(GEMINI_FLAGS) \
	    | tee $(OUTPUT_DIR)/backend-$$(date +%s).md; \
	  rm -f "$$_tmp"; \
	}

frontend: ## Dispatch Frontend Engineer (gemini-3-flash, 20 RPD)
	@mkdir -p $(OUTPUT_DIR)
	@{ \
	  _tmp=$$(mktemp /tmp/agentsquad-XXXXXX); \
	  printf '%s' "$(TASK)" > "$$_tmp"; \
	  GEMINI_API_KEY=$(FRONTEND_KEY) GEMINI_MODEL=$(FRONTEND_MODEL) \
	    gemini --prompt "$$(cat $$_tmp)" $(GEMINI_FLAGS) \
	    | tee $(OUTPUT_DIR)/frontend-$$(date +%s).md; \
	  rm -f "$$_tmp"; \
	}

qa: ## Dispatch QA Engineer (gemini-3-flash, 20 RPD)
	@mkdir -p $(OUTPUT_DIR)
	@{ \
	  _tmp=$$(mktemp /tmp/agentsquad-XXXXXX); \
	  printf '%s' "$(TASK)" > "$$_tmp"; \
	  GEMINI_API_KEY=$(QA_KEY) GEMINI_MODEL=$(QA_MODEL) \
	    gemini --prompt "$$(cat $$_tmp)" $(GEMINI_FLAGS) \
	    | tee $(OUTPUT_DIR)/qa-$$(date +%s).md; \
	  rm -f "$$_tmp"; \
	}

devops: ## Dispatch DevOps Engineer (gemini-3-flash, 20 RPD)
	@mkdir -p $(OUTPUT_DIR)
	@{ \
	  _tmp=$$(mktemp /tmp/agentsquad-XXXXXX); \
	  printf '%s' "$(TASK)" > "$$_tmp"; \
	  GEMINI_API_KEY=$(DEVOPS_KEY) GEMINI_MODEL=$(DEVOPS_MODEL) \
	    gemini --prompt "$$(cat $$_tmp)" $(GEMINI_FLAGS) \
	    | tee $(OUTPUT_DIR)/devops-$$(date +%s).md; \
	  rm -f "$$_tmp"; \
	}

consult: ## Dispatch Business Consultant (gemini-3-flash + Google Search)
	@mkdir -p $(OUTPUT_DIR)
	@{ \
	  _tmp=$$(mktemp /tmp/agentsquad-XXXXXX); \
	  printf '%s' "$(TASK)" > "$$_tmp"; \
	  GEMINI_API_KEY=$(CONSULT_KEY) GEMINI_MODEL=$(CONSULT_MODEL) \
	    gemini --prompt "$$(cat $$_tmp)" $(GEMINI_FLAGS) \
	    | tee $(OUTPUT_DIR)/consult-$$(date +%s).md; \
	  rm -f "$$_tmp"; \
	}

backend-lite: ## Backend on Gemma tier (gemma-3-27b-it, 14,400 RPD)
	@mkdir -p $(OUTPUT_DIR)
	@{ \
	  _tmp=$$(mktemp /tmp/agentsquad-XXXXXX); \
	  printf '%s' "$(TASK)" > "$$_tmp"; \
	  GEMINI_API_KEY=$(BACKEND_KEY) GEMINI_MODEL=$(GEMMA_MODEL) \
	    gemini --prompt "$$(cat $$_tmp)" $(GEMINI_FLAGS) \
	    | tee $(OUTPUT_DIR)/backend-lite-$$(date +%s).md; \
	  rm -f "$$_tmp"; \
	}

frontend-lite: ## Frontend on Gemma tier (gemma-3-27b-it, 14,400 RPD)
	@mkdir -p $(OUTPUT_DIR)
	@{ \
	  _tmp=$$(mktemp /tmp/agentsquad-XXXXXX); \
	  printf '%s' "$(TASK)" > "$$_tmp"; \
	  GEMINI_API_KEY=$(FRONTEND_KEY) GEMINI_MODEL=$(GEMMA_MODEL) \
	    gemini --prompt "$$(cat $$_tmp)" $(GEMINI_FLAGS) \
	    | tee $(OUTPUT_DIR)/frontend-lite-$$(date +%s).md; \
	  rm -f "$$_tmp"; \
	}

qa-lite: ## QA on Gemma tier (gemma-3-27b-it, 14,400 RPD)
	@mkdir -p $(OUTPUT_DIR)
	@{ \
	  _tmp=$$(mktemp /tmp/agentsquad-XXXXXX); \
	  printf '%s' "$(TASK)" > "$$_tmp"; \
	  GEMINI_API_KEY=$(QA_KEY) GEMINI_MODEL=$(GEMMA_MODEL) \
	    gemini --prompt "$$(cat $$_tmp)" $(GEMINI_FLAGS) \
	    | tee $(OUTPUT_DIR)/qa-lite-$$(date +%s).md; \
	  rm -f "$$_tmp"; \
	}

team-health: ## Check credentials are configured (0 RPD)
	@~/.agent-team/scripts/health-check.sh --cheap

team-health-live: ## Ping all agents via API (5 RPD via gemma-3-1b-it)
	@~/.agent-team/scripts/health-check.sh --live

test: ## Run pytest suite
	@uv run pytest tests/ -v

lint: ## Run ruff linter
	@uv run ruff check src/

typecheck: ## Run mypy type checker
	@uv run mypy src/

dev: ## Run agent-track CLI
	@uv run agent-track --help

clean-output: ## Remove all generated files from agent-output/
	@rm -f $(OUTPUT_DIR)/*.md $(OUTPUT_DIR)/*.py $(OUTPUT_DIR)/*.sql \
	  $(OUTPUT_DIR)/*.json $(OUTPUT_DIR)/*.sh $(OUTPUT_DIR)/*.txt
	@echo "agent-output/ cleaned"

help: ## Show this help message
	@grep -hE '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | \
	  awk 'BEGIN {FS = ": *## "}; {printf "  \033[36m%-20s\033[0m %s\n", $$1, $$2}'
